/*4a*/ SELECT VEHICLE.VEH_VIN, VEH_MAKE, VEH_MODEL, VST_LAST, VST_FIRST
	FROM VEHICLE INNER JOIN VISITOR
    ON VEHICLE.VEH_VIN = VISITOR.VEH_VIN 
    WHERE VST_DL BETWEEN 50000000 AND 50000000 + 50000000; /*George Tang*/    
/*4b*/ SELECT VEHICLE.VEH_VIN, VEH_MAKE, VEH_MODEL, EMP_LAST, EMP_FIRST
	FROM VEHICLE INNER JOIN EMPLOYEE
    ON VEHICLE.VEH_VIN = EMPLOYEE.VEH_VIN 
    WHERE EMP_SSN IN (793145862, 426852000 - 207); /*George Tang*/
/*4c*/ SELECT VEH_MAKE, VEH_MODEL FROM VEHICLE
    WHERE VEH_VIN IN (SELECT VEH_VIN FROM EMPLOYEE); /*George Tang*/
/*4d*/ SELECT VEH_MAKE FROM VEHICLE
	WHERE VEH_FOREIGN = 1
	GROUP BY VEH_MAKE HAVING COUNT(VEH_MAKE) > 1; /*George Tang*/  
/*4e*/ SELECT VEH_MODEL FROM VEHICLE
    WHERE VEH_VIN IN (SELECT VEH_VIN FROM VISITOR
    WHERE VST_LAST = "Jayne"); /*George Tang*/  
/*4e*/ SELECT VEHICLE.VEH_VIN, EMP_SSN, EMP_LAST, EMP_FIRST
	FROM VEHICLE INNER JOIN EMPLOYEE
    ON VEHICLE.VEH_VIN = EMPLOYEE.VEH_VIN 
    WHERE EMPLOYEE.VEH_VIN="WBXPA93465WA75116" AND EMP_SSN=362957841; /*George Tang*/
    