CREATE TABLE EMPLOYEE (
	VEH_VIN CHAR(17) PRIMARY KEY, 
    EMP_SSN DECIMAL(9,0) NOT NULL UNIQUE,
    EMP_LAST CHAR(50), 
    EMP_FIRST CHAR(20),
    FOREIGN KEY (VEH_VIN) references VEHICLE (VEH_VIN)
);