CREATE TABLE VISITOR (
	VEH_VIN CHAR(17) PRIMARY KEY, 
    VST_DL DECIMAL(8,0) NOT NULL UNIQUE,
    VST_LAST CHAR(50), 
    VST_FIRST CHAR(20),
    FOREIGN KEY (VEH_VIN) references VEHICLE (VEH_VIN)
);